# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.7'

gem 'activerecord', '~> 8.0'
gem 'dotenv', '~> 3.1'
gem 'pg', '~> 1.6'
gem 'puma', '~> 6.6'
gem 'rack-cors', '~> 2.0'
gem 'rackup', '~> 2.2'
gem 'rake', '~> 13.2'
gem 'jwt', '~> 2.10'
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.1'

group :test do
  gem 'rack-test', '~> 2.2'
  gem 'rspec', '~> 3.13'
  gem 'simplecov', '~> 0.22'
end
